# Generated by Django 2.0.3 on 2018-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20180530_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
