# Generated by Django 2.0.3 on 2018-03-26 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20180321_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstatus',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_question_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionstatus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_question_done', to='assessment.Question'),
        ),
    ]
