# Generated by Django 2.0.3 on 2018-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20180326_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
