# Generated by Django 2.0.3 on 2018-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20180405_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_essay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='essayresponse',
            name='essay',
            field=models.TextField(),
        ),
    ]
