# Generated by Django 2.0.3 on 2018-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20180409_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayresponse',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
