# Generated by Django 2.0.3 on 2018-05-30 19:09

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(default=None, upload_to=course.models.scramble_uploaded_filename, verbose_name='Uploaded Audio'),
        ),
    ]
