# Generated by Django 2.0.3 on 2018-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_unitassessmentcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitassessmentcompleted',
            name='show_unit',
            field=models.BooleanField(default=False),
        ),
    ]
