# Generated by Django 2.0.3 on 2018-06-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_unitassessmentcompleted_show_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitassessmentcompleted',
            name='completed',
        ),
    ]
