# Generated by Django 2.0.3 on 2018-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_unitassessmentcompleted_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitassessmentcompleted',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unitassessmentcompleted',
            name='show_unit',
            field=models.BooleanField(default=True),
        ),
    ]
