# Generated by Django 2.0.3 on 2018-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='label',
            field=models.TextField(),
        ),
    ]
