# Generated by Django 2.0.3 on 2018-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('R', 'REG'), ('S', 'STUDENT'), ('U', 'UNKWON')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='stage',
            name='user_stage',
            field=models.CharField(choices=[('G', 'GRADUATED'), ('U', 'UNGRADUATED'), ('I', 'IN CLASS')], default='I', max_length=1),
        ),
    ]
