# Generated by Django 2.0.3 on 2018-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180402_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
