# Generated by Django 2.0.3 on 2018-04-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stage_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='is_active',
        ),
    ]
