# Generated by Django 2.0.3 on 2018-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_stage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='user_stage',
            field=models.CharField(choices=[('G', 'GRADUATED'), ('U', 'UNGRADUATED'), ('I', 'IN CLASS'), ('N', 'NOT STUDENT')], default='N', max_length=1),
        ),
    ]
