# Generated by Django 2.0.3 on 2018-04-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180410_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
