# Generated by Django 2.0.3 on 2018-06-04 13:26

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20180410_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_certificate', models.FileField(upload_to=accounts.models.scramble_uploaded_filename, verbose_name='certificates_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
