# Generated by Django 2.0.3 on 2018-06-04 13:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user_certificate',
            field=models.FileField(upload_to=accounts.models.scramble_uploaded_filename, verbose_name='Certificates'),
        ),
    ]
